#Concatenating Strings - Python
"""
You are familiar with different tricks of output. Here is the last one of concatenating the string. You have two strings and your task is to print the string after concatenating them.

Hint: Use "+" to concatenate strings.

#Input:
Geeks
Code

#Output:
Geeks Code

#Explanation:
Geeks and Code are two different strings. Output is generated by concatenating them using "+".
"""

#solution.py
def print_fun(string1, string2):
    
    print (string1 + string2)
